// Code generated by go test ./media/internal/wirets -update; DO NOT EDIT.

export const MAX_SINGLE_PUT = 67108864;
export const MIN_PART_SIZE = 8388608;
export const MAX_PART_SIZE = 16777216;

export type ErrorCode = "invalid_request" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "incomplete" | "not_uploaded" | "too_many_files" | "too_large" | "quota_exceeded" | "type_not_allowed" | "checksum_mismatch" | "rate_limited" | "internal_error";

export type OpName = "insert" | "replace" | "move" | "rename" | "remove" | "edit";
export type PosterSource = "frame" | "upload" | "auto";

export const HOVER_PREVIEW_DEFAULT = 3;
export const HOVER_PREVIEW_MIN = 1;
export const HOVER_PREVIEW_MAX = 6;

export interface RefBody {
  kind: string;
  id: string;
  version?: string;
}

export interface PresignBody {
  ref: RefBody;
  type: string;
  size: number;
  sha256?: string;
  slot?: string;
  inline?: boolean;
}

export interface RequestReply {
  method: string;
  url: string;
  headers: Record<string, string>;
  expires: string;
}

export interface MultipartReply {
  ticket: string;
  min_part_size: number;
  max_part_size: number;
  max_parts: number;
}

export interface PresignReply {
  name: string;
  exists?: boolean;
  put?: RequestReply;
  multipart?: MultipartReply;
}

export interface PartBody {
  number: number;
  size: number;
  sha256: string;
}

export interface PartsBody {
  ticket: string;
  parts: PartBody[];
}

export interface TicketBody {
  ticket: string;
}

export interface PartReply {
  number: number;
  size?: number;
  sha256?: string;
  request?: RequestReply;
}

export interface PartsReply {
  parts: PartReply[];
}

export interface CompleteReply {
  name: string;
  type: string;
  size: number;
}

export interface Crop {
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface Edit {
  crop?: Crop;
  rotate?: number;
}

export interface Op {
  op: OpName;
  name: string;
  original?: string;
  index?: number;
  to?: string;
  meta?: Record<string, unknown>;
  edit?: Edit;
}

export interface CommitBody {
  ref: RefBody;
  ops: Op[];
}

export interface CommitFile {
  name: string;
  original: string;
  type?: string;
  size?: number;
  edit?: Edit;
  meta?: Record<string, unknown>;
}

export interface CommitReply {
  files: CommitFile[];
}

export interface SlotBody {
  ref: RefBody;
  slot: string;
  sha256: string;
  edit?: Edit;
}

export interface SlotFromFileBody {
  ref: RefBody;
  slot: string;
  from?: RefBody;
  file: string;
  edit?: Edit;
}

export interface SlotEditBody {
  ref: RefBody;
  slot: string;
  edit?: Edit;
}

export interface SlotRefBody {
  ref: RefBody;
  slot: string;
}

export interface Dims {
  w: number;
  h: number;
}

export interface SlotImage {
  name: string;
  w: number;
  h: number;
  url: string;
}

export interface SlotManifest {
  aspect: number;
  edit?: Edit;
  dims?: Dims;
  version?: string;
  outputs: SlotImage[];
  pending: boolean;
  error?: string;
}

export interface VideoImagesBody {
  ref: RefBody;
  file?: string;
}

export interface VideoPosterBody {
  ref: RefBody;
  source: PosterSource;
  file?: string;
  time?: number;
  sha256?: string;
  edit?: Edit;
}

export interface VideoPreviewBody {
  ref: RefBody;
  file?: string;
  start?: number;
  duration?: number;
}

export interface PosterSelection {
  source: PosterSource;
  version?: string;
  file?: string;
  time?: number;
}

export interface PosterManifest extends SlotManifest {
  selection?: PosterSelection;
}

export interface HoverPreviewSelection {
  version?: string;
  file: string;
  start: number;
  duration: number;
  auto?: boolean;
}

export interface PreviewImage {
  w: number;
  h: number;
  url: string;
}

export interface HoverPreviewManifest {
  selection?: HoverPreviewSelection;
  version?: string;
  mp4: PreviewImage[];
  webp: PreviewImage[];
  pending: boolean;
}

export interface VideoInfo {
  version?: string;
  file: string;
  duration: number;
  w: number;
  h: number;
  encoded: boolean;
}

export interface VideoImages {
  poster: PosterManifest;
  hover_preview: HoverPreviewManifest;
  video?: VideoInfo;
}

export interface ErrorReply {
  error: string;
  code: ErrorCode;
  retry_after?: number;
  originals?: string[];
}
