// Code generated by go test ./media/internal/wirets -update; DO NOT EDIT.

export const MAX_SINGLE_PUT = 67108864;
export const MIN_PART_SIZE = 8388608;
export const MAX_PART_SIZE = 16777216;

export type ErrorCode = "invalid_request" | "unauthorized" | "forbidden" | "not_found" | "conflict" | "incomplete" | "not_uploaded" | "too_many_files" | "too_large" | "quota_exceeded" | "type_not_allowed" | "checksum_mismatch" | "rate_limited" | "image_too_small" | "image_too_large" | "image_unreadable" | "animation_not_allowed" | "animation_too_long" | "animation_unsupported" | "internal_error";

export type OpName = "insert" | "attach" | "replace" | "move" | "rename" | "remove" | "edit";
export type PosterSource = "frame" | "upload" | "auto";
export type EncodePhase = "queued" | "downloading" | "probing" | "encoding" | "muxing" | "uploading" | "publishing" | "images";

export interface RefBody {
  kind: string;
  id: string;
  version?: string;
}

export interface PresignBody {
  ref: RefBody;
  type: string;
  size: number;
  sha256?: string;
  slot?: string;
  inline?: boolean;
}

export interface RequestReply {
  method: string;
  url: string;
  headers: Record<string, string>;
  expires: string;
}

export interface MultipartReply {
  ticket: string;
  min_part_size: number;
  max_part_size: number;
  max_parts: number;
}

export interface PresignReply {
  name: string;
  exists?: boolean;
  put?: RequestReply;
  multipart?: MultipartReply;
  process_on_upload?: boolean;
}

export interface PartBody {
  number: number;
  size: number;
  sha256: string;
}

export interface PartsBody {
  ticket: string;
  parts: PartBody[];
}

export interface TicketBody {
  ticket: string;
}

export interface PartReply {
  number: number;
  size?: number;
  sha256?: string;
  request?: RequestReply;
}

export interface PartsReply {
  parts: PartReply[];
}

export interface CompleteReply {
  name: string;
  type: string;
  size: number;
}

export interface Crop {
  x: number;
  y: number;
  w: number;
  h: number;
}

export interface Edit {
  crop?: Crop;
  rotate?: number;
}

export interface Op {
  op: OpName;
  name: string;
  original?: string;
  index?: number;
  to?: string;
  meta?: Record<string, unknown>;
  edit?: Edit;
  unattached?: boolean;
}

export interface CommitBody {
  ref: RefBody;
  ops: Op[];
}

export interface CommitFile {
  name: string;
  original: string;
  type?: string;
  size?: number;
  edit?: Edit;
  meta?: Record<string, unknown>;
  unattached?: boolean;
}

export interface CommitReply {
  files: CommitFile[];
}

export interface SlotBody {
  ref: RefBody;
  slot: string;
  sha256: string;
  edit?: Edit;
  filename?: string;
}

export interface SlotFromFileBody {
  ref: RefBody;
  slot: string;
  from?: RefBody;
  file: string;
  edit?: Edit;
}

export interface SlotEditBody {
  ref: RefBody;
  slot: string;
  edit?: Edit;
}

export interface SlotRefBody {
  ref: RefBody;
  slot: string;
}

export interface Dims {
  w: number;
  h: number;
}

export interface SlotImage {
  w: number;
  h: number;
  url: string;
}

export interface ErrorDetails {
  width?: number;
  height?: number;
  min_width?: number;
  max_pixels?: number;
  type?: string;
  allowed?: string[];
  size?: number;
  max_bytes?: number;
  frames?: number;
  max_frames?: number;
  seconds?: number;
  max_seconds?: number;
}

export interface SlotManifest {
  aspect: string;
  edit?: Edit;
  dims?: Dims;
  outputs: SlotImage[];
  pending: boolean;
  error?: string;
  error_code?: string;
  error_details?: ErrorDetails;
  min_width?: number;
  animation?: string;
  editor_url?: string;
}

export interface VideoImagesBody {
  ref: RefBody;
  file?: string;
}

export interface VideoPosterBody {
  ref: RefBody;
  source: PosterSource;
  file?: string;
  time?: number;
  sha256?: string;
  edit?: Edit;
}

export interface PosterSelection {
  source: PosterSource;
  version?: string;
  file?: string;
  time?: number;
}

export interface PosterManifest extends SlotManifest {
  file?: string;
  time?: number;
  selection?: PosterSelection;
}

export interface VideoInfo {
  version?: string;
  file: string;
  duration: number;
  w: number;
  h: number;
  encoded: boolean;
}

export interface VideoImages {
  poster: PosterManifest;
  video?: VideoInfo;
  progress?: EncodeProgress;
}

export interface ErrorReply {
  error: string;
  code: ErrorCode;
  retry_after?: number;
  originals?: string[];
  details?: ErrorDetails;
}

export interface ReadResult {
  access: string;
  total: number;
  preview_limit: number;
  offset: number;
  limit: number;
  expires: number;
  meta?: Record<string, unknown>;
  files: FileInfo[];
  downloads?: DownloadInfo[];
}

export interface FileInfo {
  index: number;
  name?: string;
  type?: string;
  w?: number;
  h?: number;
  duration?: number;
  edit?: Edit;
  dims?: Dims;
  teaser?: boolean;
  locked?: boolean;
  hls?: boolean;
  unattached?: boolean;
  failed?: string;
  failed_code?: string;
  failed_details?: ErrorDetails;
  progress?: EncodeProgress;
  variant?: string;
  url?: string;
}

export interface DownloadInfo {
  key: string;
  name: string;
  type?: string;
  size?: number;
  url: string;
}

export interface EncodeProgress {
  phase: EncodePhase;
  queue_position?: number;
  segments_done?: number;
  segments_total?: number;
  percent: number;
  speed?: number;
  eta?: number;
  at: number;
  stalled?: boolean;
  stage?: number;
  stages?: number;
}

export interface FilesBody {
  ref: RefBody;
  names?: string[];
}

export interface FilesReply {
  files: FileInfo[];
}
