package contract

import (
	"bytes"
	"fmt"
	"reflect"
	"strings"

	"github.com/open-rails/contentkit/internal/httpapi"
)

const docsHeader = "<!-- Generated by `go generate ./internal/contract` from the route catalog. Do not edit. -->\n"

var moduleTitles = map[httpapi.Module]string{
	httpapi.Content:  "Content: config, posts, comments, reactions, favorites, polls, bans, moderation",
	httpapi.Upload:   "Media uploads",
	httpapi.Media:    "Media reads and playback",
	httpapi.Codes:    "Content codes",
	httpapi.Taxonomy: "Taxonomy admin",
}

func (m *model) bodyDoc(v any) string {
	switch body := v.(type) {
	case nil:
		return "—"
	case httpapi.Stream:
		return "`" + strings.Split(body.ContentType, ";")[0] + "`"
	}
	return "`" + m.tsType(reflect.TypeOf(v)) + "`"
}

// routesMD is the route tables, by module, and the error codes.
func (m *model) routesMD() []byte {
	var b bytes.Buffer
	b.WriteString(docsHeader)
	b.WriteString("\n# Routes\n\n")
	fmt.Fprintf(&b, "Every route of ContentKit's HTTP API (%d). `contentkit.Runtime.Handler` serves them under the one prefix the host mounts it at, each module at its sub-path: ", len(m.routes))
	var mounts []string
	for _, mod := range httpapi.Modules {
		p := mod.Prefix()
		if p == "" {
			p = "/"
		}
		mounts = append(mounts, fmt.Sprintf("%s `%s`", mod, p))
	}
	b.WriteString(strings.Join(mounts, ", ") + ". ")
	b.WriteString("A host that mounts a module alone serves its routes beneath that mount instead. ")
	b.WriteString("Request and response names are the schemas of [`api/openapi.json`](../../api/openapi.json), which also lists each route's query parameters and error codes.\n\n")
	b.WriteString("**Tier** is what a route requires of its caller: `public` (the actor is optional; the host's resolver decides what it sees), `user` (a signed-in actor, else 401 `unauthorized`), `staff` (the `content.Perms` permission named, else 403 `forbidden`). ContentKit never authenticates: it reads the actor the host's middleware put in the request context.\n\n")
	b.WriteString("Every error is `{\"error\", \"code\", …}`; the codes are at the end.\n")
	for _, mod := range httpapi.Modules {
		var list []httpapi.Spec
		for _, r := range m.routes {
			if r.Module == mod {
				list = append(list, r)
			}
		}
		if len(list) == 0 {
			continue
		}
		p := mod.Prefix()
		if p == "" {
			p = "/"
		}
		fmt.Fprintf(&b, "\n## %s (`%s`)\n\n", moduleTitles[mod], p)
		b.WriteString("| Method | Path | Tier | Request | Response | Description |\n|---|---|---|---|---|---|\n")
		for _, r := range list {
			tier := string(r.Auth)
			if r.Perm != "" {
				tier += " `" + r.Perm + "`"
			}
			var replies []string
			for _, reply := range r.Responses {
				replies = append(replies, fmt.Sprintf("%d %s", reply.Status, m.bodyDoc(reply.Body)))
			}
			desc := r.Doc
			if len(r.Query) > 0 {
				var names []string
				for _, q := range r.Query {
					names = append(names, "`"+q.Name+"`")
				}
				desc += " Query: " + strings.Join(names, ", ") + "."
			}
			fmt.Fprintf(&b, "| %s | `%s` | %s | %s | %s | %s |\n", r.Method, r.FullPath(), tier, m.bodyDoc(r.Request), strings.Join(replies, "<br>"), strings.ReplaceAll(desc, "|", "\\|"))
		}
	}
	b.WriteString("\n## Error codes\n\n")
	b.WriteString("Clients branch on `code`; `error` is a message for people and may change.\n\n")
	b.WriteString("| Code | Status | Meaning |\n|---|---|---|\n")
	for _, c := range httpapi.ErrorCodes() {
		fmt.Fprintf(&b, "| `%s` | %d | %s |\n", c.Code, c.Status, c.Meaning)
	}
	return b.Bytes()
}
