package contract

import (
	"bytes"
	"fmt"
	"reflect"
	"sort"
	"strings"

	"github.com/open-rails/contentkit/internal/httpapi"
	"github.com/open-rails/contentkit/media"
)

const tsHeader = "// Generated by `go generate ./internal/contract` from ContentKit's route catalog. Do not edit.\n"

// tsType is t as a TypeScript type.
func (m *model) tsType(t reflect.Type) string {
	t = elem(t)
	k, _ := classify(t)
	switch k {
	case kindString:
		if values := m.enums.of(t); values != nil {
			return union(values)
		}
		return "string"
	case kindTime:
		return "string"
	case kindInteger, kindNumber:
		return "number"
	case kindBoolean:
		return "boolean"
	case kindAny:
		return "unknown"
	case kindArray:
		return tsElem(m.tsType(t.Elem())) + "[]"
	case kindMap:
		return "Record<string, " + m.tsType(t.Elem()) + ">"
	}
	return m.names[t]
}

func union(values []string) string {
	quoted := make([]string, len(values))
	for i, v := range values {
		quoted[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(quoted, " | ")
}

// tsElem parenthesizes a union element type.
func tsElem(s string) string {
	if strings.Contains(s, " | ") {
		return "(" + s + ")"
	}
	return s
}

func tsKey(name string) string {
	for i, r := range name {
		ok := r == '_' || r >= 'a' && r <= 'z' || r >= 'A' && r <= 'Z' || (i > 0 && r >= '0' && r <= '9')
		if !ok {
			return fmt.Sprintf("%q", name)
		}
	}
	return name
}

// wireTS is every wire type. A member is optional when Go omits it empty; a
// request-only type's pointer members are optional too (omitted means
// unchanged), and a content.Nullable one also takes null (clears). A response
// member Go writes as null when unset is `| null`.
func (m *model) wireTS() []byte {
	var b bytes.Buffer
	b.WriteString(tsHeader)
	b.WriteString("\nimport type { ErrorCode } from \"./error-codes.js\";\n\nexport type { ErrorCode };\n")
	fmt.Fprintf(&b, "\n// Upload sizes: one PUT up to MAX_SINGLE_PUT bytes, else multipart parts.\nexport const MAX_SINGLE_PUT = %d;\nexport const MIN_PART_SIZE = %d;\nexport const MAX_PART_SIZE = %d;\n",
		media.MaxSinglePut, media.MinPartSize, media.MaxPartSize)
	b.WriteString("\n")
	for _, e := range enums {
		if e.name == "ErrorCode" {
			continue
		}
		fmt.Fprintf(&b, "export type %s = %s;\n", e.name, union(e.values))
	}
	for _, o := range m.sortedObjects() {
		fmt.Fprintf(&b, "\nexport interface %s {\n", o.name)
		for _, f := range o.fields {
			t := m.tsType(f.t)
			if name := m.enumOf(f); name != "" {
				t = name
			}
			opt := ""
			switch {
			case f.clears:
				opt, t = "?", t+" | null"
			case f.optional, !o.output && f.t.Kind() == reflect.Pointer:
				opt = "?"
			case f.nullable && o.output:
				t += " | null"
			}
			fmt.Fprintf(&b, "  %s%s: %s;\n", tsKey(f.name), opt, t)
		}
		b.WriteString("}\n")
	}
	return b.Bytes()
}

// bodyTS names a body's TypeScript type, or null for none.
func (m *model) bodyTS(v any) string {
	switch body := v.(type) {
	case nil:
		return "null"
	case httpapi.Stream:
		return fmt.Sprintf("%q", body.ContentType)
	}
	return fmt.Sprintf("%q", m.tsType(reflect.TypeOf(v)))
}

// routesTS is the route table: each route's module, path, tier and the names
// of its request and response types in wire.ts.
func (m *model) routesTS() []byte {
	var b bytes.Buffer
	b.WriteString(tsHeader)
	b.WriteString(`
export type ContentKitModule = ` + union(moduleNames()) + `;

// Each module's sub-path under the one mount (contentkit.Runtime.Handler).
export const CONTENTKIT_MODULES: Readonly<Record<ContentKitModule, string>> = {
`)
	for _, mod := range httpapi.Modules {
		fmt.Fprintf(&b, "  %s: %q,\n", mod, mod.Prefix())
	}
	b.WriteString(`};

export type ContentKitRoute = {
  method: "GET" | "POST" | "PUT" | "PATCH" | "DELETE";
  module: ContentKitModule;
  // The path from the module's mount: CONTENTKIT_MODULES[module] + path under the one mount.
  path: string;
  // public: the actor is optional; user: a signed-in actor; staff: the host permission.
  auth: "public" | "user" | "staff";
  // A staff route's content.Perms field.
  permission: string | null;
  query: readonly string[];
  // wire.ts type names (or a content type): the JSON body, and each success by status.
  request: string | null;
  responses: Readonly<Record<number, string | null>>;
  // The route's own codes, and the shared sets (CONTENTKIT_ERROR_SETS) it also answers.
  errors: readonly string[];
  errorSets: readonly string[];
};

export const CONTENTKIT_ROUTES = [
`)
	sets := map[string][]string{}
	for _, r := range m.routes {
		perm := "null"
		if r.Perm != "" {
			perm = fmt.Sprintf("%q", r.Perm)
		}
		var replies []string
		seen := map[int]bool{}
		for _, reply := range r.Responses {
			if seen[reply.Status] {
				continue // a second body under one status: see openapi.json
			}
			seen[reply.Status] = true
			replies = append(replies, fmt.Sprintf("%d: %s", reply.Status, m.bodyTS(reply.Body)))
		}
		var query []string
		for _, q := range r.Query {
			query = append(query, q.Name)
		}
		fmt.Fprintf(&b, "  { method: %q, module: %q, path: %q, auth: %q, permission: %s, query: [%s], request: %s, responses: { %s }, errors: [%s], errorSets: [%s] },\n",
			r.Method, r.Module, r.Path, r.Auth, perm, quoted(query), m.bodyTS(r.Request), strings.Join(replies, ", "), quoted(r.Errors), quoted(r.ErrorSets()))
		for _, name := range r.ErrorSets() {
			sets[name] = httpapi.ErrorSet(name)
		}
	}
	b.WriteString("] as const satisfies readonly ContentKitRoute[];\n")
	names := make([]string, 0, len(sets))
	for name := range sets {
		names = append(names, name)
	}
	sort.Strings(names)
	b.WriteString("\n// The codes every route of a kind answers, by set name.\nexport const CONTENTKIT_ERROR_SETS: Readonly<Record<string, readonly string[]>> = {\n")
	for _, name := range names {
		fmt.Fprintf(&b, "  %q: [%s],\n", name, quoted(sets[name]))
	}
	b.WriteString("};\n")
	return b.Bytes()
}

func moduleNames() []string {
	var out []string
	for _, mod := range httpapi.Modules {
		out = append(out, string(mod))
	}
	return out
}

// errorCodesTS is the error-code registry: every code with its status and
// meaning.
func errorCodesTS() []byte {
	codes := httpapi.ErrorCodes()
	var b bytes.Buffer
	b.WriteString("// Generated by `go generate ./internal/contract` from ContentKit's error-code registry. Do not edit.\n\n")
	b.WriteString("export type ErrorCode =\n")
	for _, c := range codes {
		fmt.Fprintf(&b, "  | %q\n", c.Code)
	}
	b.WriteString(";\n\n// Each code's HTTP status and meaning. A message on the wire is for people;\n// classify by code.\nexport const CONTENTKIT_ERROR_CODES: Readonly<Record<ErrorCode, { status: number; meaning: string }>> = {\n")
	for _, c := range codes {
		meaning, _ := marshal(c.Meaning)
		fmt.Fprintf(&b, "  %s: { status: %d, meaning: %s },\n", tsKey(c.Code), c.Status, meaning)
	}
	b.WriteString("};\n")
	return b.Bytes()
}

func quoted(list []string) string {
	out := make([]string, len(list))
	for i, s := range list {
		out[i] = fmt.Sprintf("%q", s)
	}
	return strings.Join(out, ", ")
}
