// Package wirets renders the upload API wire types as TypeScript for the
// browser SDK (sdk/upload/src/wire.gen.ts). The test keeps the file current:
//
//	go test ./media/internal/wirets -update
package wirets

import (
	"fmt"
	"reflect"
	"strings"
	"time"

	"github.com/open-rails/contentkit/media"
)

var types = []any{
	media.RefBody{}, media.PresignBody{}, media.RequestReply{}, media.MultipartReply{}, media.PresignReply{},
	media.PartBody{}, media.PartsBody{}, media.TicketBody{}, media.PartReply{}, media.PartsReply{},
	media.CompleteReply{}, media.Crop{}, media.Edit{}, media.Op{}, media.CommitBody{}, media.CommitFile{},
	media.CommitReply{}, media.SlotBody{}, media.SlotFromFileBody{}, media.ErrorReply{},
}

var errorCodes = []string{
	media.CodeInvalid, "unauthorized", media.CodeForbidden, media.CodeNotFound, media.CodeConflict,
	media.CodeIncomplete, media.CodeNotUploaded, media.CodeTooManyFiles, media.CodeTooLarge, media.CodeQuota, media.CodeType,
	media.CodeChecksum, media.CodeRate, "internal_error",
}

var ops = []string{media.OpInsert, media.OpReplace, media.OpMove, media.OpRename, media.OpRemove, media.OpEdit}

// Render returns the TypeScript source.
func Render() string {
	var b strings.Builder
	b.WriteString("// Code generated by go test ./media/internal/wirets -update; DO NOT EDIT.\n\n")
	fmt.Fprintf(&b, "export const MAX_SINGLE_PUT = %d;\nexport const MIN_PART_SIZE = %d;\nexport const MAX_PART_SIZE = %d;\n\n",
		media.MaxSinglePut, media.MinPartSize, media.MaxPartSize)
	fmt.Fprintf(&b, "export type ErrorCode = %s;\n\n", union(errorCodes))
	fmt.Fprintf(&b, "export type OpName = %s;\n", union(ops))
	for _, v := range types {
		t := reflect.TypeOf(v)
		fmt.Fprintf(&b, "\nexport interface %s {\n", t.Name())
		for i := range t.NumField() {
			f := t.Field(i)
			name, opts, _ := strings.Cut(f.Tag.Get("json"), ",")
			if name == "-" || !f.IsExported() {
				continue
			}
			if name == "" {
				name = f.Name
			}
			typ := ts(f.Type)
			if t.Name() == "Op" && name == "op" {
				typ = "OpName"
			}
			if t.Name() == "ErrorReply" && name == "code" {
				typ = "ErrorCode"
			}
			opt := ""
			if strings.Contains(opts, "omitempty") || f.Type.Kind() == reflect.Pointer {
				opt = "?"
			}
			fmt.Fprintf(&b, "  %s%s: %s;\n", name, opt, typ)
		}
		b.WriteString("}\n")
	}
	return b.String()
}

func union(vs []string) string {
	q := make([]string, len(vs))
	for i, v := range vs {
		q[i] = fmt.Sprintf("%q", v)
	}
	return strings.Join(q, " | ")
}

func ts(t reflect.Type) string {
	if t == reflect.TypeOf(time.Time{}) {
		return "string"
	}
	switch t.Kind() {
	case reflect.Pointer:
		return ts(t.Elem())
	case reflect.String:
		return "string"
	case reflect.Bool:
		return "boolean"
	case reflect.Int, reflect.Int8, reflect.Int16, reflect.Int32, reflect.Int64,
		reflect.Uint, reflect.Uint8, reflect.Uint16, reflect.Uint32, reflect.Uint64, reflect.Float32, reflect.Float64:
		return "number"
	case reflect.Slice:
		return ts(t.Elem()) + "[]"
	case reflect.Map:
		return "Record<" + ts(t.Key()) + ", " + ts(t.Elem()) + ">"
	case reflect.Interface:
		return "unknown"
	case reflect.Struct:
		return t.Name()
	}
	panic("wirets: unsupported type " + t.String())
}
