name: scan
'on':
  pull_request:
    branches: [master]
  workflow_call: {}
permissions:
  contents: read
concurrency:
  group: scan-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true
jobs:
  injection-scan:
    uses: open-rails/helpers/.github/workflows/injection-scan.yml@6201c38329794f36e6b0cc19d850c4c4125451d5
